### PR TITLE
Future Stuff.

### PR DESCRIPTION
**Pull request by DerpfacePython**
At last! I have finally completed everything!

@qlstudio, can you put your lotto stuff into this update before doing the pull request? Thanks!

### CODE REVIEW

**Comment by qlstudio** [comment]
THANK YOU FOR DELETING THE MERGING CONFLICTS!!!!!

**Comment by qlstudio** [comment]
Oh dear, merging conflicts

**Comment by DerpfacePython** [comment]
Is there any way to view the merging conflicts?

**Comment by DerpfacePython** [comment]
Hello? @qlstudio?

**Comment by qlstudio** [comment]
Oh... sorry. I don't think so, but there is something in GithubHelp about merging conflicts. Just use Git Command Line

**Comment by DerpfacePython** [comment]
Before you fix the conflicts, @qlstudio, can you add your lotto update in the code?

**Comment by qlstudio** [comment]
Sure. I'm on it right now (more difficult than i thought...)

**Comment by qlstudio** [comment]
@DerpfacePython  now i'm gonna use cmd for the conflicts

**Pull request merged**
