### PR TITLE
More improvements, including moving more logic into the model class

### PR DESCRIPTION
**Pull request by joshgit**
More improvements, including moving more logic into the model class

### CODE REVIEW

**Comment by qlstudio** [comment]
> This branch has conflicts that must be resolved

*GRRRRR!*

**Comment by joshgit** [comment]
How do we see the conflicts?

**Comment by DerpfacePython** [comment]
Whoa...

Hang on, I might want to fix up the game.py a bit. Can you wait a while?

**Comment by joshgit** [comment]
No, fix it after these changes. :(

**Comment by DerpfacePython** [comment]
@qlstudio @joshgit Some queries/issues I currently have.

- What's with the `initialize_vars` and `frames.py` and stuff?
- What's with all the `globals()` calls? They seem pretty redundant to me.
- I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested this for me and the game has broke because of that).
- The function `log` is a bit redundant. I know you want to bug-test it and all, @joshgit, but we can fix it without `log`.

Some things I have implemented:

- All the updates of 0.7.2.
- A potential fix for the auto-updater.

**Comment by qlstudio** [comment]
Remember that Python 3 only supports accessing globals and not creating globals

**Comment by joshgit** [comment]
initialize_vars has been in there.
frames.py is GUI companents.
log has been in there.
The globals calls have been in there.

> I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested the game for me - albeit for an earlier version - and the game has broke because of the number being too large).

If that's the case you should add the steps to reproduce the bug.  But I don't believe it happens in this version of the game anyway.

**Comment by joshgit** [comment]
> Remember that Python 3 only supports accessing globals and not creating globals

I don't see anything that says that.  Where did you see this?

**Comment by qlstudio** [comment]
Python 3 doesn't support creating a global variable named "l" in function "f" just by doing this:

```python
def f():
    global l
    l = 5
    ...

```

**Comment by qlstudio** [comment]
> I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested the game for me - albeit for an earlier version - and the game has broke because of the number being too large).

we are using a different algorithm (namely ASCII-85 encoding)

**Comment by joshgit** [comment]
> Python 3 doesn't support creating a global variable named "l" in function "f" just by doing this:

Says who???

**Comment by qlstudio** [comment]
I did it before.

**Comment by joshgit** [comment]
It seems to work now.  How else do you work with globals?  Show me a link that substantiates this, please.

**Comment by testitem** [comment]
Huh? YOU KNOW THAT I DID version 3.0.7.1. It was APPROVED to work.

**Comment by testitem** [comment]
I'm actually QlStudio. I deleted my account (LOL)

**Comment by joshgit** [comment]
> YOU KNOW THAT I DID version 3.0.7.1. It was APPROVED to work.

What does that mean?

**Comment by testitem** [comment]
This is the proof that I did it: https://github.com/DerpfacePython/Ways-to-NOT-make-money/commit/3f5d45b80ff629851a90ea0d892d334d519d8008

**Comment by joshgit** [comment]
Proof that you did what?

**Comment by testitem** [comment]
That I did version 3.0.7.1

**Comment by joshgit** [comment]
What is that version?  Why are you talking about this?

**Comment by testitem** [comment]
Python 3 Version 0.7.1 (I did that)

**Comment by testitem** [comment]
HELLO???

**Comment by joshgit** [comment]
Ok, why are you telling me that?

**Comment by testitem** [comment]
I created the initialize_vars() function in version 3.0.7.1. It was the only way to make the program WORK. run your program. see if it works

**Comment by testitem** [comment]
I may be wrong, but then it's python's problem.

**Comment by joshgit** [comment]
Oh, I get it!  Thanks. :)  I did test it without that function and it does work.

**Comment by testitem** [comment]
Oh well. Sorry.

**Comment by testitem** [comment]
I WISH THAT @DerpfacePython  WOULD ADD ME AS A COLLABORATOR

**Comment by DerpfacePython** [comment]
Hang on, can you get rid of the globals() calls for Python 2, @joshgit or @testitem? Thanks.

**Comment by joshgit** [comment]
Don't we need those class?

**Comment by testitem** [comment]
> Don't we need those calls?

I'm pretty sure we do...

**Comment by testitem** [comment]
IMPORTANT: Please DO NOT MERGE. Merging conflicts cause distortions to the executable and the single file executable, which is (almost) impossible to fix. Just let me copy-paste the code when you say it's approved.

**Comment by DerpfacePython** [comment]
Hang on, @joshgit, @testitem, can one of you test the Pything (Python thing... going to call it Pything from now on) - gamePy2.py - without the globals and check if it works?

**Comment by joshgit** [comment]
@DerpfacePython Most of game.py is GUI-related stuff, including the deduction* functions.  bugfixer() and lotto() are game logic that I think we should move into the game_model class.  If we do that, all the game logic will be in the model and the main file will be all GUI stuff.

**Comment by DerpfacePython** [comment]
@joshgit So sometimes when you buy a building, the building number displayed gets "clogged", I.e. it doesn't move up. That's what `bugfixer()` is for.

**Comment by DerpfacePython** [comment]
@testitem, can you fix up the exe and sfexe so that they're zipped? Maybe that could help with the conflicts a little bit - also, rearrange the files so that they match (almost) exactly with the layout that the master branch is at currently. @joshgit, you need to be active more.

**Comment by josh-valant** [comment]
What should I do?

**Comment by joshgit** [comment]
What should I do?

**Comment by DerpfacePython** [comment]
@joshgit Uh... heh heh... I was mainly saying that because you didn't reply to my pull request.

**Comment by testitem** [comment]
Could you keep the compare branch up-to-date with the base branch so we don't have conflicts from now on? Thank you.

**Comment by DerpfacePython** [comment]
@testitem Can you change all the file formatting so that they're exact with the current version?

**Comment by testitem** [comment]
no. I need to wait until @joshgit  adds me as a collaborator for his Ways-to-not-make-money fork. I couldn't edit his repo files.

**Comment by joshgit** [comment]
Why do you need to be a collaborator?

**Comment by testitem** [comment]
@DerpfacePython told me to edit some files in your fork repo to make it up to date or it's impossible to merge the pull request.

**Comment by testitem** [comment]
JUST DO IT.

**Comment by testitem** [comment]
@joshgit @DerpfacePython @Cyber-Shadow  by the way, I may not be active June 23 - July 1

**Comment by joshgit** [comment]
@testitem so clone it and send me a pull request?

**Comment by testitem** [comment]
sure. uh.. that's going to be difficult... (Why the heck does my computer lose the git clt every time when I want to use it?)

**Comment by testitem** [comment]
Actually, I can only fix conflicts for the exe things. If I fix all conflicts it's going to overwrite the pull request.

**Comment by testitem** [comment]
I am replacing this pull request with one that has conflicts fixed since don't have push access to joshgit/ways-to-not-make-money

**Comment by joshgit** [comment]
@testitem can't you just send me a pull request?  Is this not how github works?

**Comment by testitem** [comment]
Well, git terminal isn't letting me push to my fork... I do not know why.

**Pull request closed without merging**
