### PR TITLE
print("one clicked") will not work for py2 use eval('print("one click…

### PR DESCRIPTION
**Pull request by testitem**
…ed")') instead.

THE CURRENT FRAMES.PY WILL NOT WORK FOR PY2. @Cyber-Shadow I'm just letting you know.

### CODE REVIEW

**Comment by DerpfacePython** [comment]
So... are the pythons merged? What's the deal with `gamePy3.py`?

**Comment by testitem** [comment]
uh... what do you mean?

**Comment by DerpfacePython** [comment]
Why is `gamePy3.py` still there?

**Comment by DerpfacePython** [comment]
As well as that, @joshgit, @testitem, the -illions are in `save_and_load`, but not in `game_model` or `game`. Should we put millions into all of them or get rid of it (and put it back in if the problem persists)?

**Comment by joshgit** [comment]
@DerpfacePython I don't see -illions in my save_and_load file.  Can you show me the exact line?  Did a bad merge happen?

What are you talking about re: "Also, the parameter callback isn't in bf" ?  Can you show us a line number or stack trace?

I'm suspicious about these problems suddenly cropping up at this point.

**Comment by Cyber-Shadow** [comment]
Do everyone a favor by getting rid of the python 3 version.

**Comment by joshgit** [comment]
@Cyber-Shadow That is stupid.

**Comment by DerpfacePython** [comment]
@joshgit, @Cyber-Shadow has a point - we're merging the Py2 and Py3 versions anyway. I'm just not sure if @qlstudio is finished with merging it yet.

**Comment by joshgit** [comment]
So there's the problem with ButtonFrame, which you said you fixed, and the problem with -illions which you caused...  What are the remaining problems?

**Comment by DerpfacePython** [comment]
The ButtonFrame issue isn't fixed yet - @testitem fixed it so that the print statement would work properly with the lambda. There's still no third argument on `bf`, so I was just wondering what it is.

**Comment by joshgit** [comment]
That's in the GameFrame class, which isn't used right now, right?  What would you use for the 3rd argument?

**Comment by DerpfacePython** [comment]
I have no idea, TBH, @joshgit. I thought you put it there.

**Comment by testitem** [comment]
WELL THE PY2EXE WON'T LET ME COMPILE GameFrame WITH CODE ERRORS, @joshgit .

**Comment by testitem** [comment]
I merged Py2 and Py3, @DerpfacePython . @joshgit , yell at me if there are errors.

**Comment by DerpfacePython** [comment]
So wait... who made `frames`?

**Comment by testitem** [comment]
@joshgit did. His pull request (#97 ) was superseded by mine (#107 )

**Comment by joshgit** [comment]
@testitem just add an argument...

**Comment by DerpfacePython** [comment]
@joshgit Shouldn't you add an argument, since you made frames and understand the situation better than both of us can?

**Comment by joshgit** [comment]
No, just read the code. :D

**Comment by testitem** [comment]
wait.. i meant #108 .

@joshgit , does game.py work for both Python 2 and Python 3?

**Comment by testitem** [comment]
> EDIT: Not all the problems are with you, @joshgit (but most of them still are, anyway): the -illions thing was my fault, I included in auto_updater.

The -illions thing aren't needed in Python 3 because Python 3 doesn't convert huge numbers into different data types.  The OverflowError happened when Python 2 didn't convert the huge number (How the heck that happened I still do not truly know,) into a long int. We could actually fix it by only storing x, y, and z in the equation (money = x10^y + z), also displaying it in the same format. The stumbling block is when y gets huge, x is a whole number and z is a number like 32187637246234. Then z generates an OverflowError... The -illions thing is better. But what if the money amount goes higher than 2147483647 quintillion? The only way to fix this bug is to use the Python 3 version since Python 3 allows integers above 2147483647.

**Comment by testitem** [comment]
(Continued from previous post)

Why is @Cyber-Shadow hate Python 3 so much? Python 3 can make fixing the -illions bug way easier than fixing it in Python 2.

SIDE NOTE: Wow why the heck did I change my passcode into a thirty-digit one?

**Comment by DerpfacePython** [comment]
@testitem It's kind of an in-joke between me and @Cyber-Shadow, TBH.

**Comment by testitem** [comment]
oh.

**Comment by testitem** [comment]
Is there anything we have to add for 0.7.3? (I got rid of the version.major.minor.patch format since we merged the game.) If not, I'll merge the pull request. @DerpfacePython @joshgit ***IF NO ONE RESPONDS BY 12:00 PM 5-30 EDT, I WILL MERGE THE PULL REQUEST WITHOUT NOTICE.***

**Comment by testitem** [comment]
So no one replied.

**Comment by testitem** [comment]
I guess no one saw this anyways. @DerpfacePython are you going to merge this or NOT?

**Comment by DerpfacePython** [comment]
Hello, sorry about not replying. I'm slightly busy at the moment, with exams going on - I didn't really have time to reply.

**Comment by testitem** [comment]
Oh. Thanks!

**Pull request merged**
