### PR TITLE
Updated game.py to V0.7.0

### PR DESCRIPTION
**Pull request by DerpfacePython**
I'm merging the future thing to here, fix whatever you need to., @qlstudio.

### CODE REVIEW

**Comment by DerpfacePython** [comment]
I thought you were going to fix stuff...

**Comment by qlstudio** [comment]
wait whhhaaaattttttt?

**Comment by DerpfacePython** [comment]
You know, like all the logouts and stuff that I left out.

**Comment by qlstudio** [comment]
yeah- i'm going to copy it back in

**Comment by qlstudio** [comment]
oh dear

**Comment by qlstudio** [comment]
fixed!!!

**Pull request merged**
