### PR TITLE
Change game.py to v0.6.2

### PR DESCRIPTION
**Pull request by qlstudio**
0.6.2 fixed issue #10 and #11.

### CODE REVIEW

**Comment by DerpfacePython** [comment]
I already have an update planned, though... and all the problems have been fixed.
[game.txt](https://github.com/DerpfacePython/Ways-to-NOT-make-money/files/63922/game.txt)
(I can only upload game.py in txt format, because of github).

P.S. How did you come to our game?

**Comment by qlstudio** [comment]
Where is the savefile? I want to test run it!

**Comment by qlstudio** [comment]
Now I changed the code in my fork, but it's IMPOSSIBLE to run without savefile
(actually, once I HACKED the code and tried to figure the right savefile myself)

**Comment by DerpfacePython** [comment]
Oh... whoops. Here is the savefile.
[savefile.txt](https://github.com/DerpfacePython/Ways-to-NOT-make-money/files/64946/savefile.txt)

**Comment by qlstudio** [comment]
You actually merged your own game.txt in, but im not gonna complain about that
Thanks for the new version!

**Pull request merged**
