### PR TITLE
Update to v0.6.4alpha1 (Randomness Update)

### PR DESCRIPTION
**Pull request by qlstudio**
This release adds a new function which adds or deducts from your money randomly.

TODO:

- [x] Money Lotto
- [ ] MPS Lotto
- [x] Store lotto price in savefile

### CODE REVIEW

**Comment by qlstudio** [comment]
Find out for yourself which things have which probabilities.

**Comment by DerpfacePython** [comment]
What does this lotto thing do?

Also, we seriously don't need the issue reporting thing, just saying.

**Comment by qlstudio** [comment]
Fine... do you really want to delete the issue reporting thing? Maybe you can ignore it, but some users might find it useful.

Merging in 1 day

**Comment by qlstudio** [comment]
Merging.

**Comment by DerpfacePython** [comment]
But we don't need it...

**Comment by DerpfacePython** [comment]
What does the Lotto thing do? I might implement it into the `future` branch (which could be implemented into `main`).

**Comment by DerpfacePython** [comment]
What? No, I just want to ask what the Lotto thing does, and how it works and stuff. I might implement it.

**Comment by qlstudio** [comment]
It's just like earn or lose a certain amount of money under a probability (losing money is more common....)

hopefully you can figure the probs:

    money -= lottoprice
    lottoprice *= uniform(1.1, 5.1)
    prob = random()
    if prob < (1/3.0): # 1/3 probability
         money += 50.0
    elif prob < (1/3.0 + 1/5.0): # 1/5 prob
         money += 120.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0): # 1/7 prob
         money += 200.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0): # 1/9 prob
         money += 260.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0 + 1/11.0): # 1/11 prob
         money += 500.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0 + 1/11.0 + 1/13.0): # 1/13 prob
         money += 600.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0 + 1/11.0 + 1/13.0 + 1/1013.0): # 1/1013 prob
         money += 50000.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0 + 1/11.0 + 1/13.0 + 1/1013.0 + 1/2013.0): # 1/2013 prob
         money += 250000.0
    elif prob < (1/3.0 + 1/5.0 + 1/7.0 + 1/9.0 + 1/11.0 + 1/13.0 + 1/1013.0 + 1/2013.0 + 1/3013.0): # 1/3013 prob
         money += 153250000.0
    else:
         money = 1000.0 # hee hee hee...

**Comment by qlstudio** [comment]
oh check this out

https://github.com/qlstudio/MyVirtualCity

**Comment by DerpfacePython** [comment]
What does `uniform()` do?

**Comment by qlstudio** [comment]
Nearly same as random() just random decimal selection in range [1.1, 5.1)

**Comment by qlstudio** [comment]
didit... 2 more days

**Comment by DerpfacePython** [comment]
Did what?

**Comment by qlstudio** [comment]
PR

**Comment by qlstudio** [comment]
Now?

**Pull request merged**
