### PR TITLE
Update game.py to V0.7.2

### PR DESCRIPTION
**Pull request by DerpfacePython**
Removed the animation bar thing, and replaced it with a notification box.

Also made the code neater.

### CODE REVIEW

**Comment by DerpfacePython** [comment]
I think the code in `game.py` is really messy - I suggest splitting it up into smaller chunks, and just maybe have `main()` and `mainloop()` (maybe other required functions) in the main `game.py`, and have the rest of the functions in different files.

What do you guys think (I'm probably only going to talk to @qlstudio, but eh)?

**Comment by qlstudio** [comment]
> I think the code in game.py is really messy - I suggest splitting it up into smaller chunks, and just maybe have main() and mainloop() (maybe other required functions) in the main game.py, and have the rest of the functions in different files. That way, everything would be easier to find and code.

Definitely - the actual game.py should then just be in a package and renamed "__init__.py" or "__main__.py" or whatever showing it is the file you'd have to run, but it could just be game.py

> Also, the exe and the single-file-executable folder names should be changed, so that it doesn't contain the version name (the version changes a lot, so the name won't stick for very long - include the version stuff in the README.)

Sure.

SIDE NOTE:
# ***DO NOT COMMIT TO MASTER UNTIL MERGED!***

**Comment by DerpfacePython** [comment]
Oh yeah, the savefile needs to update as well.

**Comment by qlstudio** [comment]
What do you mean - savefile???

And sorting would be difficult...

**Comment by DerpfacePython** [comment]
Wait... don't pull-request it yet. I need to update the savefile.

**Comment by DerpfacePython** [comment]
Because I changed the animation-bar thing, we can probably get rid of these pictures.

**Comment by qlstudio** [comment]
We can DELETE the savefile. The savefile is CREATED by the program.

**Comment by qlstudio** [comment]
Because Py3 diverged...

**Comment by DerpfacePython** [comment]
What do you mean "Py3 diverged"?

**Comment by qlstudio** [comment]
Py2 is ahead and behind Py3. Py3 is ahead and behind Py2.

**Comment by DerpfacePython** [comment]
Ah. Got that. But does it really have to be exactly the same? I mean, some subtle differences could work.

**Comment by joshgit** [comment]
What??

**Comment by DerpfacePython** [comment]
No wait, ignore that comment, I forgot @joshgit's commit to fix that.

But yeah, the code doesn't have to be exactly the same, like same classes, same functions, that sort of thing. IMO, as long as the GUI is the same, and the code works the same, it's the same to me.

**Comment by joshgit** [comment]
Do all the pulls!

**Pull request merged**
