### PR TITLE
Revert "Update game.py to V0.7.2"

### PR DESCRIPTION
**Pull request by qlstudio**
Reverts DerpfacePython/Ways-to-NOT-make-money#90

### CODE REVIEW

**Comment by DerpfacePython** [comment]
Wait... why is it reverted?

**Comment by qlstudio** [comment]
I fixed the diverging...

**Comment by qlstudio** [comment]
Could you re-implement 0.7.2? Because if i copy from the commit it would overwrite @joshgit 's changes to Py2.

**Comment by joshgit** [comment]
Did I change py2/ ?

**Comment by qlstudio** [comment]
No. I implemented the SAME changes to py3 as from py2/

**Comment by joshgit** [comment]
Come to the irc channel!  freenode, #waystonotmakemoney

**Comment by qlstudio** [comment]
That includes you, @DerpfacePython

**Comment by DerpfacePython** [comment]
Yeah, I went in.

**Pull request merged**
