### PR TITLE
Updated game.py to V0.7.0-alpha2

### PR DESCRIPTION
**Pull request by DerpfacePython**
DO NOT PLAY YET - It doesn't work.

I need someone - anyone - to fix the scrollbar thing, because I have NO IDEA HOW.

DON'T MERGE UNTIL SCROLLBAR IS FIXED.

### CODE REVIEW

**Comment by qlstudio** [comment]
Hey.... where is the bug??

**Comment by qlstudio** [comment]
Oh dear... *why* are we needing the scrollbar again?

**Comment by DerpfacePython** [comment]
Ugh... @Cyber-Shadow wanted to add a few, and it would make the game better later on...

**Comment by qlstudio** [comment]
Oh. However, since this is a future branch, can't we merge it, fix it in future branch, and *then* merge to master?

**Comment by DerpfacePython** [comment]
Oh, yeah... forgot about that. But this version isn't playable at all, so I have no idea what to do.

**Comment by qlstudio** [comment]
Doesn't the future branch README say "download at your own risk, since there are many bugs"? (Or something similar)

**Comment by DerpfacePython** [comment]
Oh. OK, then.

**Comment by DerpfacePython** [comment]
Merged!

**Pull request merged**
