### PR TITLE
Fix for Tkinter threading issue

### PR DESCRIPTION
**Pull request by joshgit**

### CODE REVIEW

**Comment by DerpfacePython** [comment]
What exactly does this update do?

**Comment by joshgit** [comment]
No, that's all it's trying to do.  Replacing threading with events is pretty easy here, but it's not exactly a tiny, simple swap.

**Comment by DerpfacePython** [comment]
Oh... ah.

**Comment by DerpfacePython** [comment]
Oh, what.

**Comment by qlstudio** [comment]
The 0.7 code is in game_07.py - you could just look in the file's history (game.py > History > Bug-fixing Galore! > View)

**Comment by DerpfacePython** [comment]
Oh, whoops...
Should have seen.

**Pull request merged**
