### PR TITLE
#97

### PR DESCRIPTION
**Pull request by testitem**
same thing as #97

### CODE REVIEW

**Comment by testitem** [comment]
@joshgit ??

**Comment by joshgit** [comment]
Hello, can I help you?

**Comment by testitem** [comment]
This is the same thing as #97 that's why I closed the pr

**Comment by testitem** [comment]
Refresher:
```
 More improvements, including moving more logic into the model class #97
Closed
joshgit wants to merge 12 commits into DerpfacePython:master from joshgit:master
+952 −2,129
Conversation 50 Commits 12 Files changed 8
enhancement
help wanted
py2version
py3version
No milestone
No one—
Notifications

You’re receiving notifications because you were mentioned.
3 participants
@joshgit
@DerpfacePython
@testitem
Lock conversation
@joshgit
Collaborator
joshgit commented 9 days ago

More improvements, including moving more logic into the model class
joshgit added some commits 15 days ago
	@joshgit 	fix for game_model not loading lottoprice 		
	a92b9dd
	@joshgit 	fixed lotto price, market share price updating, and money image cycling 		
	a8a1a03
	@joshgit 	fixing money formating and removing extra -illions in save data 		
	f807394
	@joshgit 	fixing prices 		
	97d60e1
	@joshgit 	fixed encoding problem with saving … 		
	7e68e2c
	@joshgit 	consolidating upgrade callbacks 		
	74b23ac
	@joshgit 	Defuctoring GUI to use events instead of polling for initial frames 			f913bcc
	@joshgit 	fixing money saving 			2009fa6
	@joshgit 	game saves and loads GameState without using intermediary data/g2 list 			183c595
	@joshgit 	moving game logic to model class 			b1edc54
	@joshgit 	backporting changes to py2 version 			2b65924
@ghost
ghost commented 9 days ago

    This branch has conflicts that must be resolved

GRRRRR!
@joshgit
Collaborator
joshgit commented 9 days ago

How do we see the conflicts?
@DerpfacePython DerpfacePython added enhancement py3version labels 9 days ago
@DerpfacePython
Owner
DerpfacePython commented 9 days ago • edited

Whoa...

Hang on, I might want to fix up the game for py2 a bit. Can you wait a while?
@DerpfacePython DerpfacePython added help wanted py2version labels 9 days ago
@joshgit
Collaborator
joshgit commented 9 days ago • edited

No, fix it after these changes. :(

@joshgit Or we can fix it right now, and it saves us the time of making a new pull request and stuff. (TBH, I just want to do something...)
@DerpfacePython
Owner
DerpfacePython commented 8 days ago • edited

@qlstudio @joshgit Some queries/issues I currently have.

    What's with the initialize_vars and frames.py and stuff?
    What's with all the globals() calls? They seem pretty redundant to me.
    I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested the game for me - albeit for an earlier version - and the game has broke because of the number being too large).
    The function log is a bit redundant. I know you want to bug-test it and all, @joshgit, but we can fix it without log.

Some things I have implemented:

    All the updates of 0.7.2.
    A potential fix for the auto-updater.

@ghost
ghost commented 8 days ago

Remember that Python 3 only supports accessing globals and not creating globals
@joshgit
Collaborator
joshgit commented 8 days ago • edited

initialize_vars has been in there.
frames.py is GUI companents.
log has been in there.
The globals calls have been in there.

    I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested the game for me - albeit for an earlier version - and the game has broke because of the number being too large).

If that's the case you should add the steps to reproduce the bug. But I don't believe it happens in this version of the game anyway. If it does still happen, we should just fix the way it save/loads, which should be pretty easy.
@joshgit
Collaborator
joshgit commented 8 days ago

    Remember that Python 3 only supports accessing globals and not creating globals

I don't see anything that says that. Where did you see this?
Changes you viewed 7 days ago
	@joshgit 	removing initialize_vars function 			d7c6fd7
@ghost
ghost commented 8 days ago

Python 3 doesn't support creating a global variable named "l" in function "f" just by doing this:

def f():
    global l
    l = 5
    ...

@ghost
ghost commented 8 days ago

    I think we should definitely keep the millions and stuff in the savefile (OverflowError does happen, someone has playtested the game for me - albeit for an earlier version - and the game has broke because of the number being too large).

we are using a different algorithm (namely ASCII-85 encoding)
@joshgit
Collaborator
joshgit commented 8 days ago

    Python 3 doesn't support creating a global variable named "l" in function "f" just by doing this:

Says who???
@ghost
ghost commented 8 days ago

I did it before.
@joshgit
Collaborator
joshgit commented 8 days ago

It seems to work now. How else do you work with globals? Show me a link that substantiates this, please.
@testitem
Collaborator
testitem commented 7 days ago

Huh? YOU KNOW THAT I DID version 3.0.7.1. It was APPROVED to work.
@testitem
Collaborator
testitem commented 7 days ago

I'm actually QlStudio. I deleted my account (LOL)
@joshgit
Collaborator
joshgit commented 7 days ago

    YOU KNOW THAT I DID version 3.0.7.1. It was APPROVED to work.

What does that mean?
@testitem
Collaborator
testitem commented 7 days ago

This is the proof that I did it: 3f5d45b
@joshgit
Collaborator
joshgit commented 7 days ago

Proof that you did what?
@testitem
Collaborator
testitem commented 7 days ago

That I did version 3.0.7.1
@joshgit
Collaborator
joshgit commented 7 days ago

What is that version? Why are you talking about this?
@testitem
Collaborator
testitem commented 7 days ago

Python 3 Version 0.7.1 (I did that)
@testitem
Collaborator
testitem commented 7 days ago

HELLO???
@joshgit
Collaborator
joshgit commented 7 days ago

Ok, why are you telling me that?
@testitem
Collaborator
testitem commented 7 days ago

I created the initialize_vars() function in version 3.0.7.1. It was the only way to make the program WORK. run your program. see if it works
@testitem
Collaborator
testitem commented 7 days ago

I may be wrong, but then it's python's problem.
@joshgit
Collaborator
joshgit commented 7 days ago • edited

Oh, I get it! Thanks. :) I did test it without that function and it does work, at least as far as I saw.
@testitem
Collaborator
testitem commented 7 days ago

Oh well. Sorry.
@testitem
Collaborator
testitem commented 7 days ago

I WISH THAT @DerpfacePython WOULD ADD ME AS A COLLABORATOR
@DerpfacePython
Owner
DerpfacePython commented 6 days ago

Hang on, can you get rid of the globals() calls for Python 2, @joshgit or @testitem? Thanks.
@joshgit
Collaborator
joshgit commented 6 days ago • edited

Don't we need those calls?
@testitem
Collaborator
testitem commented 6 days ago

    Don't we need those calls?

I'm pretty sure we do...
@testitem
Collaborator
testitem commented 6 days ago

IMPORTANT: Please DO NOT MERGE. Merging conflicts cause distortions to the executable and the single file executable, which is (almost) impossible to fix. Just let me copy-paste the code when you say it's approved.
@DerpfacePython
Owner
DerpfacePython commented 5 days ago • edited

Hang on, @joshgit, @testitem, can one of you test the Pything (Python thing... going to call it Pything from now on) - gamePy2.py - without the globals and check if it works?

Also, just asking, @joshgit, is there a way to move all the building functions (e.g. "deduction1h1", "boostauto3" etc.) into a new file? We could save a heckuva lot of lines in the main file.
@joshgit
Collaborator
joshgit commented 5 days ago • edited

@DerpfacePython Most of game.py is GUI-related stuff, including the deduction* functions. bugfixer() and lotto() are game logic that I think we should move into the game_model class. If we do that, all the game logic will be in the model and the main file will be all GUI stuff.

Do you remember what was the point of bugfixer() exactly? Will it work at all if I just remove it?
@DerpfacePython
Owner
DerpfacePython commented 5 days ago • edited

@joshgit So sometimes when you buy a building, the building number displayed gets "clogged", I.e. it doesn't move up. That's what bugfixer() is for.

Also, I feel that game.py is pretty cluttered, in my opinion. Too many lines.

@testitem, maybe next time you should merge one pull request at a time, in order, so that we don't have conflicts.
@DerpfacePython
Owner
DerpfacePython commented 3 days ago

@testitem, can you fix up the exe and sfexe so that they're zipped? Maybe that could help with the conflicts a little bit - also, rearrange the files so that they match (almost) exactly with the layout that the master branch is at currently. @joshgit, you need to be active more.
@joshgit
Collaborator
joshgit commented 3 days ago

What should I do?
@DerpfacePython
Owner
DerpfacePython commented 2 days ago

@joshgit Uh... heh heh... I was mainly saying that because you didn't reply to my pull request.
@testitem
Collaborator
testitem commented 2 days ago

Could you keep the compare branch up-to-date with the base branch so we don't have conflicts from now on? Thank you.
@DerpfacePython
Owner
DerpfacePython commented 2 days ago

@testitem Can you change all the file formatting so that they're exact with the current version?
@testitem
Collaborator
testitem commented 21 hours ago

no. I need to wait until @joshgit adds me as a collaborator for his Ways-to-not-make-money fork. I couldn't edit his repo files.
@joshgit
Collaborator
joshgit commented 21 hours ago

Why do you need to be a collaborator?
@testitem
Collaborator
testitem commented 20 hours ago

@DerpfacePython told me to edit some files in your fork repo to make it up to date or it's impossible to merge the pull request.
@testitem
Collaborator
testitem commented 20 hours ago

JUST DO IT.
@testitem
Collaborator
testitem commented 20 hours ago

@joshgit @DerpfacePython @Cyber-Shadow by the way, I may not be active June 23 - July 1
@joshgit
Collaborator
joshgit commented 20 hours ago

@testitem so clone it and send me a pull request?
@testitem
Collaborator
testitem commented 6 hours ago

sure. uh.. that's going to be difficult... (Why the heck does my computer lose the git clt every time when I want to use it?)
@testitem
Collaborator
testitem commented 6 hours ago

Actually, I can only fix conflicts for the exe things. If I fix all conflicts it's going to overwrite the pull request.
@testitem
Collaborator
testitem commented 5 hours ago

I am replacing this pull request with one that has conflicts fixed since don't have push access to joshgit/ways-to-not-make-money
@testitem testitem closed this 5 hours ago
@testitem testitem referenced this pull request 5 hours ago
Open
#97 #108
@joshgit
Collaborator
joshgit commented 4 hours ago

@testitem can't you just send me a pull request? Is this not how github works?
@testitem
Collaborator
testitem commented just now

Well, git terminal isn't letting me push to my fork... I do not know why.
```

**Comment by DerpfacePython** [comment]
Ah. Might need to patch up the auto-updater thing.

**Comment by DerpfacePython** [comment]
Should we merge the py2 and py3 versions together in this update as well?

**Comment by testitem** [comment]
# ***@joshgit @DerpfacePython PLEASE DO NOT COMMIT TO MASTER UNTIL MERGED!***

**Comment by testitem** [comment]
> Should we merge the py2 and py3 versions together in this update as well?

I did recently.

**Comment by DerpfacePython** [comment]
What? Where? It's not merged yet.

**Comment by joshgit** [comment]
Ok, I'm committing to master.

**Comment by testitem** [comment]
Did not.

What were you going to commit to master for anyways?? Do it after this PR is merged

**Comment by DerpfacePython** [comment]
Wait, did not what?

**Comment by testitem** [comment]
did not commit to master branch

**Comment by testitem** [comment]
I'm guessing we can merge this? feel free to revert it.

**Pull request merged**
