### PR TITLE
Updated game.py to V0.6.1

### PR DESCRIPTION
**Pull request by DerpfacePython**
Needs to be fixed!!!

### CODE REVIEW

**Comment by DerpfacePython** [comment]
This game still isn't complete yet, as it can't run. qlstudio, can you manage to get it to run (_without_ putting the variables inside a function)?

**Comment by qlstudio** [comment]
I get this error when I run it:

    Traceback (most recent call last):
      File "C:/Python27/Ways-to-NOT-make-money-master/game.py", line 1135, in <module>
        upgcheck1h1 = int(g2[9])
    NameError: global name 'g2' is not defined

**Comment by qlstudio** [comment]
OK, sure, I can merge it, but I don't want it to be confused with the 0.6.2. If we are sure that the game is working, I can delete the 0.6.2 game.py and replace it with the 0.6.1 (newer) game.py...

**Comment by qlstudio** [comment]
The new merged game is game061-pending, the old game is game062

**Pull request merged**
